version: '3'

services:
  neo4jdb:
    container_name: neo4j_anibook
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
      - '7473:7473'
    environment:
      - NEO4J_AUTH=neo4j/anibook_qa
      - NEO4J_HOME=/var/lib/neo4j
    volumes:
      - ./config/csv:/var/lib/neo4j/import