version: '3'

services:
  neo4jdb:
    container_name: neo4j_estante
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
      - '7473:7473'
    environment:
      - NEO4J_AUTH=neo4j/neo4j12#456